app/__init__.py
# app/__init__.py

from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from .routes import bp as routes_bp  # Update this line to use 'bp'

db = SQLAlchemy()

def create_app():
    # Create the Flask create_app instance
    app = Flask(__name__)

    # Configure my database connection
    app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql+mysqlconnector://root:new_password@34.224.63.159/RecomMix?auth_plugin=mysql_native_password'
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

    # Initialize the database
    db.init_app(app)
    # Register my blueprints and other configurations here
    app.register_blueprint(routes_bp)  # Update this line to use 'routes_bp'

    return app

app/routes.py
# app/routes.py

from flask import Blueprint, render_template, Flask, request, jsonify
from .recommendation.data_processing import fetch_songs_from_api, extract_audio_features, preprocess_data, normalize_data, save_data_to_database

bp = Blueprint('routes_bp', __name__)

@bp.route('/')
def home():
    return render_template('index.html')

@bp.route('/about')
def about():
    return render_template('about.html')

@bp.route('/data_collection_and_preprocessing')
def data_collection_and_preprocessing():
    # Define my API endpoint
    api_endpoint = 'https://api.spotify.com/v1/me/tracks'

    # Step 1: Fetch songs dataset using an API
    songs_dataset = fetch_songs_from_api(api_endpoint)

    # Step 2: Extract relevant audio features
    audio_features = extract_audio_features(songs_dataset)

    # Step 3: Preprocess the dataset
    preprocessed_data = preprocess_data(audio_features)

    # Step 4: Normalize and scale audio features
    normalized_data = normalize_data(preprocessed_data)

    # Step 5: Save the preprocessed dataset for future use
    table_name = 'preprocessed_data_table'
    save_data_to_database(normalized_data, table_name)

    return "Data collection and preprocessing completed!"

# Assume playlists is a list or dictionary containing playlist data
playlists = {
    'playlist1': ['song1', 'song2', 'song3'],
    'playlist2': ['song4', 'song5'],
    # ...
}

# Route to edit a playlist
@bp.route('/api/playlists/<playlist_name>', methods=['PUT'])
def edit_playlist(playlist_name):
    try:
        # Get the new playlist name from the request JSON
        new_name = request.json['newName']
        
        # Update the playlist name
        playlists[new_name] = playlists.pop(playlist_name)
        
        return jsonify({'message': 'Playlist edited successfully'}), 200
    except KeyError:
        return jsonify({'error': 'New playlist name not provided in the request'}), 400
    except Exception as e:
        return jsonify({'error': str(e)}), 500

# Route to delete a playlist
@bp.route('/api/playlists/<playlist_name>', methods=['DELETE'])
def delete_playlist(playlist_name):
    try:
        # Delete the playlist
        del playlists[playlist_name]
        
        return jsonify({'message': 'Playlist deleted successfully'}), 200
    except KeyError:
        return jsonify({'error': f'Playlist "{playlist_name}" not found'}), 404
    except Exception as e:
        return jsonify({'error': str(e)}), 500

app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>RecomMix Recommendation System</title>
  <!-- Include my CSS styles here -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
  <script src="{{ url_for('static', filename='js/script.js') }}" defer></script>
  <script defer>
    // Highlight navigation for the 'about' page
    window.addEventListener('load', () => {
      highlightActiveLink();
    });
  </script>
  
<body>
    <nav class= "header nav">
        <ul>
            <li><a href="{{ url_for('routes_bp.home') }}">Home</a></li>
            <li><a href="{{ url_for('routes_bp.about') }}">About</a></li>
            <!-- Add other navigation links as needed -->
        </ul>
    </nav>

  <!-- Intro Section -->
  <header class="header">
   <!--  <img src="path/to/cover-image.jpg" alt="RecomMix Cover Image"> -->
    <h1 class="header__title">RecomMix</h1>
    <p>Discover Personalized Music Recommendations</p>
    <a href="link-to-deployed-app" class="btn">Visit Project</a>
  </header>
  
  <main class="main">
  <!-- Feature Section -->
  <section id="features">
    <div class="feature">
    <!--  <img src="path/to/feature1-image.jpg" alt="Feature 1 Image"> -->
      <h2>Search Songs</h2>
      <p>Find your favorite songs with our powerful search feature.</p>
    </div>
    <div class="feature">
    <!--   <img src="path/to/feature2-image.jpg" alt="Feature 2 Image"> -->
      <h2>Personalized Recommendations</h2>
      <p>Get personalized music recommendations based on my preferences.</p>
    </div>
    <div class="feature">
    <!--   <img src="path/to/feature3-image.jpg" alt="Feature 3 Image"> -->
      <h2>Create Playlists</h2>
      <p>Build and manage your own music playlists effortlessly.</p>
    </div>
  </section>

  <!-- About Section -->
  <section id="about">
    <h2>About RecomMix</h2>
    <p>RecomMix is a music recommendation system designed to provide you with a personalized music discovery experience. Our project was inspired by the love for music and the desire to create a seamless platform for finding and enjoying songs.</p>
    </section>
    <!-- Team Members -->
    <footer>
        <div class="team-member">
            <h3>Aibueku Precious Okwuoma</h3>
            <a href="https://www.linkedin.com/in/aibuekuoprecious/" target="_blank"><i class="fab fa-linkedin"></i></a>
            <a href="https://github.com/aibuekuoprecious" target="_blank"><i class="fab fa-github"></i></a>
            <a href="https://twitter.com/pre_shial" target="_blank"><i class="fab fa-twitter"></i></a>
        </div>
    </footer>
  <!-- Include my scripts here if needed -->

</body>
</html>

app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RecomMix Recommendation System</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <script src="{{ url_for('static', filename='js/script.js') }}" defer></script>
    <script defer>
        // Highlight navigation for the 'about' page
        window.addEventListener('load', () => {
          highlightActiveLink();
        });
      </script>
      
</head>
<body>
    <nav class="header nav">
        <ul>
            <li><a href="{{ url_for('routes_bp.home') }}">Home</a></li>
            <li><a href="{{ url_for('routes_bp.about') }}">About</a></li>
            <!-- Add other navigation links as needed -->
        </ul>
    </nav>

    <header class="header">
        <!--  <img src="path/to/cover-image.jpg" alt="RecomMix Cover Image"> -->
         <h1 class="header__title">RecomMix</h1>
         <p>Discover Personalized Music Recommendations</p>
    </header>
       

    <main class="main">
        <div class="container">
            <div class="search-container">
                <label for="searchInput">Search for songs:</label>
                <div class="search">
                    <input type="text" id="searchInput" class="search__input" placeholder="Enter song name...">
                    <button onclick="searchSongs()" class="search__button">Search</button>
                </div>
            </div>

            <div class="user-input-container">
                <label for="targetUser">Target User:</label>
                <input type="text" id="targetUser" class="user-input" placeholder="Enter target user">

                <label for="likedSongs">Liked Songs (comma-separated):</label>
                <input type="text" id="likedSongs" class="user-input" placeholder="Enter liked songs">
            </div>

            <div class="control-buttons">
                <button onclick="getRecommendations()" class="button button--primary">Get Recommendations</button>
            </div>

            <div id="songInfo" class="song-info-container"></div>

            <div class="playback-container">
                <audio controls id="audioPlayer" class="audio-player"></audio>
            </div>

            <div class="feedback-container">
                <button onclick="collectUserFeedback('like')" class="feedback-button feedback-button--like">Like</button>
                <button onclick="collectUserFeedback('dislike')" class="feedback-button feedback-button--dislike">Dislike</button>
            </div>

            <div class="playlist-container">
                <label for="playlistName">Playlist Name:</label>
                <input type="text" id="playlistName" class="user-input" placeholder="Enter playlist name...">

                <div class="control-buttons">
                    <button onclick="createPlaylist()" class="button button">Create Playlist</button>
                </div>
            </div>
        </div>
    </main>

    <footer>
        <div class="team-member">
            <h3>Aibueku Precious Okwuoma</h3>
            <a href="https://www.linkedin.com/in/aibuekuoprecious/" target="_blank"><i class="fab fa-linkedin"></i></a>
            <a href="https://github.com/aibuekuoprecious" target="_blank"><i class="fab fa-github"></i></a>
            <a href="https://twitter.com/pre_shial" target="_blank"><i class="fab fa-twitter"></i></a>
        </div>
    </footer>
</body>
</html>